In [1]:
# Imports
import os
import platform
import random
from tkinter import Tk

from itertools import permutations
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import numpy as np
import torch
import torchvision
from torchvision import transforms, models,datasets
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

# Extend width of Jupyter Notebook Cell to the size of browser
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# OS related settings
if platform.system() == 'Windows':
    print('Windows')
#     %matplotlib tk
    %matplotlib qt
elif platform.system() == 'Darwin':
    print('macOS')
    Tk().withdraw()
    %matplotlib osx
elif platform == 'linux' or platform == 'linux2':
    print('Linux')
# This line of "print" must exist right after %matplotlib command, otherwise JN will hang on the first import statement after this.
print('Interactive plot activated')

macOS
Interactive plot activated


In [2]:
# ChIQP

import numpy as np
import itertools
from cvxopt import solvers, matrix



# Silencing solvers.qp

from contextlib import redirect_stdout
from io import StringIO
class NullIO(StringIO):
    def write(self, txt):
        pass


def silent(fn):
    """Decorator to silence functions."""
    def silent_fn(*args, **kwargs):
        with redirect_stdout(NullIO()):
            return fn(*args, **kwargs)
    return silent_fn






class ChoquetIntegral:

    def __init__(self):
        """Instantiation of a ChoquetIntegral.
           This sets up the ChI. It doesn't take any input parameters
           because you may want to use pass your own values in(as opposed
           to learning from data). To instatiate, use
           chi = ChoquetIntegral.ChoquetIntegral()
        """
        self.trainSamples, self.trainLabels = [], []
        self.testSamples, self.testLabels = [], []
        self.N, self.numberConstraints, self.M = 0, 0, 0
        self.g = 0
        self.fm = []
        self.type = []


    def train_chi(self, x1, l1):
        """
        This trains this instance of your ChoquetIntegral w.r.t x1 and l1.
        :param x1: These are the training samples of size N x M(inputs x number of samples)
        :param l1: These are the training labels of size 1 x M(label per sample)
        """
        self.type = 'quad'
        self.trainSamples = x1
        self.trainLabels = l1
        self.N = self.trainSamples.shape[0]
        self.M = self.trainSamples.shape[1]
#         print("Number Inputs : ", self.N, "; Number Samples : ", self.M)
        self.fm = self.produce_lattice()

        return self



    def chi_quad(self, x2):
        """
        This will produce an output for this instance of the ChI
        This will use the learned(or specified) Choquet integral to
        produce an output w.r.t. to the new input.
        :param x2: testing sample
        :return: output of the choquet integral.
        """
        if self.type == 'quad':
            n = len(x2)
            pi_i = np.argsort(x2)[::-1][:n] + 1
            ch = x2[pi_i[0] - 1] * (self.fm[str(pi_i[:1])])
            for i in range(1, n):
                latt_pti = np.sort(pi_i[:i + 1])
                latt_ptimin1 = np.sort(pi_i[:i])
                ch = ch + x2[pi_i[i] - 1] * (self.fm[str(latt_pti)] - self.fm[str(latt_ptimin1)])
            return ch
        else:
            print("If using sugeno measure, you need to use chi_sugeno.")


    def produce_lattice(self):
        """
            This method builds is where the lattice(or FM variables) will be learned.
            The FM values can be found via a quadratic program, which is used here
            after setting up constraint matrices. Refer to papers for complete overview.
        :return: Lattice, the learned FM variables.
        """

        fm_len = 2 ** self.N - 1  # nc
        E = np.zeros((fm_len, fm_len))  # D
        L = np.zeros(fm_len)  # f
        index_keys = self.get_keys_index()
        for i in range(0, self.M):  # it's going through one sample at a time.
            l = self.trainLabels[i]  # this is the labels
            fm_coeff = self.get_fm_class_img_coeff(index_keys, self.trainSamples[:, i], fm_len)  # this is Hdiff
            # print(fm_coeff)
            L = L + (-2) * l * fm_coeff
            E = E + np.matmul(fm_coeff.reshape((fm_len, 1)), fm_coeff.reshape((1, fm_len)))

        G, h, A, b = self.build_constraint_matrices(index_keys, fm_len)
        solvers_qp = silent(solvers.qp)
        sol = solvers_qp(matrix(2 * E, tc='d'), matrix(L.T, tc='d'), matrix(G, tc='d'), matrix(h, tc='d'),
                         matrix(A, tc='d'), matrix(b, tc='d'))
        g = sol['x']
        Lattice = {}
        for key in index_keys.keys():
            Lattice[key] = g[index_keys[key]]
        return Lattice


    def build_constraint_matrices(self, index_keys, fm_len):
        """
        This method builds the necessary constraint matrices.
        :param index_keys: map to reference lattice components
        :param fm_len: length of the fuzzy measure
        :return: the constraint matrices
        """

        vls = np.arange(1, self.N + 1)
        line = np.zeros(fm_len)
        G = line
        line[index_keys[str(np.array([1]))]] = -1.
        h = np.array([0])
        for i in range(2, self.N + 1):
            line = np.zeros(fm_len)
            line[index_keys[str(np.array([i]))]] = -1.
            G = np.vstack((G, line))
            h = np.vstack((h, np.array([0])))
        for i in range(2, self.N + 1):
            parent = np.array(list(itertools.combinations(vls, i)))
            for latt_pt in parent:
                for j in range(len(latt_pt) - 1, len(latt_pt)):
                    children = np.array(list(itertools.combinations(latt_pt, j)))
                    for latt_ch in children:
                        line = np.zeros(fm_len)
                        line[index_keys[str(latt_ch)]] = 1.
                        line[index_keys[str(latt_pt)]] = -1.
                        G = np.vstack((G, line))
                        h = np.vstack((h, np.array([0])))

        line = np.zeros(fm_len)
        line[index_keys[str(vls)]] = 1.
        G = np.vstack((G, line))
        h = np.vstack((h, np.array([1])))

        # equality constraints
        A = np.zeros((1, fm_len))
        A[0, -1] = 1
        b = np.array([1]);

        return G, h, A, b


    def get_fm_class_img_coeff(self, Lattice, h, fm_len):  # Lattice is FM_name_and_index, h is the samples, fm_len
        """
        This creates a FM map with the name as the key and the index as the value
        :param Lattice: dictionary with FM
        :param h: sample
        :param fm_len: fm length
        :return: the fm_coeff
        """

        n = len(h)  # len(h) is the number of the samples
        fm_coeff = np.zeros(fm_len)
        pi_i = np.argsort(h)[::-1][:n] + 1
        for i in range(1, n):
            fm_coeff[Lattice[str(np.sort(pi_i[:i]))]] = h[pi_i[i - 1] - 1] - h[pi_i[i] - 1]
        fm_coeff[Lattice[str(np.sort(pi_i[:n]))]] = h[pi_i[n - 1] - 1]
        np.matmul(fm_coeff, np.transpose(fm_coeff))
        return fm_coeff


    def get_keys_index(self):
        """
        Sets up a dictionary for referencing FM.
        :return: The keys to the dictionary
        """

        vls = np.arange(1, self.N + 1)
        count = 0
        Lattice = {}
        for i in range(0, self.N):
            Lattice[str(np.array([vls[i]]))] = count
            count = count + 1
        for i in range(2, self.N + 1):
            A = np.array(list(itertools.combinations(vls, i)))
            for latt_pt in A:
                Lattice[str(latt_pt)] = count
                count = count + 1
        return Lattice



In [ ]:
# All in one


# Creating data

num_epoch = 100

dim = 5
num_per_perm_train = 10
num_per_perm_test = 10
num_train = math.factorial(dim) * num_per_perm_train
num_test = math.factorial(dim) * num_per_perm_test

eva_func_num = 4

# N! possible permutations
all_perms = list(permutations(list(range(dim))))
random.shuffle(all_perms)


# Generate Train Data
# Get a 5 times bigger superset to make sure each perm would have num_per_perm_train
train_data_superset = np.random.rand(dim, num_train*5)
train_data_perms = np.argsort(train_data_superset, 0)
# train_data_by_perm = []
train_data_superset_by_perm = []

for i, current_perm in enumerate(all_perms):
    temp = np.where(train_data_perms[0, :]==current_perm[0])
    for j, idx in enumerate(current_perm):
        temp = np.intersect1d(temp, np.where(train_data_perms[j, :]==idx))
#         if temp.size == num_per_perm_train:
#             break
    if temp.size < num_per_perm_train:
        print('Current permutation doesn\'t have sufficient number of samples. Please regenerate!')
        break
    train_data_superset_by_perm.append(temp)
print('Train data ready')
print('Train data superset size:', train_data_superset.shape)
    
# Generate Test Data
# Get a 5 times bigger superset to make sure each perm would have num_per_perm_test
test_data_superset = np.random.rand(dim, num_test*5)
test_data_perms = np.argsort(test_data_superset, 0)
# test_data_by_perm = []
test_data_superset_by_perm = []

for i, current_perm in enumerate(all_perms):
    temp = np.where(test_data_perms[0, :]==current_perm[0])
    for j, idx in enumerate(current_perm):
        temp = np.intersect1d(temp, np.where(test_data_perms[j, :]==idx))
    if temp.size < num_per_perm_test:
        print('Current permutation doesn\'t have sufficient number of samples. Please regenerate!')
        break
    test_data_superset_by_perm.append(temp)
print('Test data ready')
print('Test data superset size:', test_data_superset.shape)

    

SSEs_all = np.zeros((len(all_perms), eva_func_num))
SSEs_c_all = np.zeros((len(all_perms)-1, eva_func_num))

for epoch in range(num_epoch):
    print('Epoch', epoch)
#     train_data = np.random.rand(dim, num_train)
#     train_data_perms = np.argsort(train_data, 0)
    
#     random.shuffle(all_perms)
#     print(all_perms)

    # Divide data into N! sets according to its permutation
#     train_data_div_by_perm = []

#     print('All permutations')
#     for i, current_perm in enumerate(all_perms):
# #         print(i, current_perm)
#         temp = np.where(train_data_perms[0, :]==current_perm[0])
#         for j, idx in enumerate(current_perm):
#             temp = np.intersect1d(temp, np.where(train_data_perms[j, :]==idx))
#         train_data_div_by_perm.append(temp)


    # Test data
    # Divide data into N! sets according to its permutation
#     test_data_div_by_perm = []

#     for i, current_perm in enumerate(all_perms):
#         temp = np.where(test_data_perms[0, :]==current_perm[0])
#         for j, idx in enumerate(current_perm):
#             temp = np.intersect1d(temp, np.where(test_data_perms[j, :]==idx))
#         test_data_div_by_perm.append(temp)
        
        
    train_data_by_perm = []
    test_data_by_perm = []
    
    for i, current_perm in enumerate(all_perms):
        temp = train_data_superset_by_perm[i]
        random.shuffle(temp)
        train_data_by_perm.append(temp[0:num_per_perm_train])
        
        temp = test_data_superset_by_perm[i]
        random.shuffle(temp)
        test_data_by_perm.append(temp[0:num_per_perm_test])
        
    # Making N! train datasets with data percentage = i/N!
    train_data_ioverN_percent = [train_data_by_perm[0]]
    for i in range(1, len(all_perms)):
        train_data_iN = np.concatenate((train_data_ioverN_percent[i-1], train_data_by_perm[i]))
        random.shuffle(train_data_iN)
        train_data_ioverN_percent.append(train_data_iN)

#     print('train data size')
#     for i, data_idx in enumerate(train_data_ioverN_percent):
#         train_d = test_data_superset[:, data_idx]
#         print(train_d.shape)


    # Making N! test datasets with data percentage = i/N!
    test_data_ioverN_percent = [test_data_by_perm[0]]
    test_data_ioverN_percent_c = []
    for i in range(1, len(all_perms)):
        test_data_iN = np.concatenate((test_data_ioverN_percent[i-1], test_data_by_perm[i]))
        test_data_iN_c = list(set(range(num_test)) - set(test_data_ioverN_percent[i-1]))
        test_data_ioverN_percent.append(test_data_iN)
        test_data_ioverN_percent_c.append(test_data_iN_c)

#     print('test data size')
#     for i, data_idx in enumerate(test_data_ioverN_percent):
#         test_d = test_data[:, data_idx]
#         print(test_d.shape)

#     print('Test data complement size')
#     for i, data_idx in enumerate(test_data_ioverN_percent_c):
#         test_d_c = test_data[:, data_idx]
#         print(test_d_c.shape)

        
        
        
    
    # Train

#     eva_func_num = 4

    SSEs = np.zeros((len(all_perms), eva_func_num))
    SSEs_c = np.zeros((len(all_perms)-1, eva_func_num))

    for i, data_idx in enumerate(tqdm(train_data_ioverN_percent)):
#         print(i, 'i')
#         print('Seen data percentage:', (i+1)/math.factorial(dim))

        train_d = train_data_superset[:, data_idx]
        test_d = test_data_superset[:, test_data_ioverN_percent[i]]

        train_label_min = np.amin(train_d, 0)
        train_label_max = np.amax(train_d, 0)
        train_label_mean = np.mean(train_d, 0)
        train_label_gmean = np.cbrt(np.prod(train_d, 0))

        test_label_min = np.amin(test_d, 0)
        test_label_max = np.amax(test_d, 0)
        test_label_mean = np.mean(test_d, 0)
        test_label_gmean = np.cbrt(np.prod(test_d, 0))

        if i < len(all_perms)-1:
            test_d_c = test_data_superset[:, test_data_ioverN_percent_c[i]]

            test_label_min_c = np.amin(test_d_c, 0)
            test_label_max_c = np.amax(test_d_c, 0)
            test_label_mean_c = np.mean(test_d_c, 0)
            test_label_gmean_c = np.cbrt(np.prod(test_d_c, 0))


        chi = ChoquetIntegral()
        chi.train_chi(train_d, train_label_min)
        SSE = 0
        for j in range(np.size(test_d, 1)):
            chi_min_test = chi.chi_quad(test_d[:, j])
            SSE += (chi_min_test - test_label_min[j]) ** 2
        SSEs[i, 0] = SSE / np.size(test_d)
#         print('\nChi min', chi.fm)
#         print('\nSSE', SSE)
        if i < len(all_perms)-1:
            SSE_c = 0
            for j in range(np.size(test_d_c, 1)):
                chi_min_test_c = chi.chi_quad(test_d_c[:, j])
                SSE_c += (chi_min_test_c - test_label_min_c[j]) ** 2
            SSEs_c[i, 0] = SSE_c / np.size(test_d_c)
#             print('\nUnseen data SSE', SSE_c)


        chi = ChoquetIntegral()
        chi.train_chi(train_d, train_label_max)
        SSE = 0
        for j in range(np.size(test_d, 1)):
            chi_max_test = chi.chi_quad(test_d[:, j])
            SSE += (chi_max_test - test_label_max[j]) ** 2
        SSEs[i, 1] = SSE / np.size(test_d)
#         print('\nChi max', chi.fm)
#         print('\nSSE', SSE)
        if i < len(all_perms)-1:
            SSE_c = 0
            for j in range(np.size(test_d_c, 1)):
                chi_max_test_c = chi.chi_quad(test_d_c[:, j])
                SSE_c += (chi_max_test_c - test_label_max_c[j]) ** 2
            SSEs_c[i, 1] = SSE_c / np.size(test_d_c)
#             print('\nUnseen data SSE', SSE_c)


        chi = ChoquetIntegral()
        chi.train_chi(train_d, train_label_mean)
        SSE = 0
        for j in range(np.size(test_d, 1)):
            chi_mean_test = chi.chi_quad(test_d[:, j])
            SSE += (chi_mean_test - test_label_mean[j]) ** 2
        SSEs[i, 2] = SSE / np.size(test_d)
#         print('\nChi mean', chi.fm)
#         print('\nSSE', SSE)
        if i < len(all_perms)-1:
            SSE_c = 0
            for j in range(np.size(test_d_c, 1)):
                chi_mean_test_c = chi.chi_quad(test_d_c[:, j])
                SSE_c += (chi_mean_test_c - test_label_mean_c[j]) ** 2
            SSEs_c[i, 2] = SSE_c / np.size(test_d_c)
#             print('\nUnseen data SSE', SSE_c)


        chi = ChoquetIntegral()
        chi.train_chi(train_d, train_label_gmean)
        SSE = 0
        for j in range(np.size(test_d, 1)):
            chi_gmean_test = chi.chi_quad(test_d[:, j])
            SSE += (chi_gmean_test - test_label_gmean[j]) ** 2
        SSEs[i, 3] = SSE / np.size(test_d)
#         print('\nChi geometric mean', chi.fm)
#         print('\nSSE', SSE)
        if i < len(all_perms)-1:
            SSE_c = 0
            for j in range(np.size(test_d_c, 1)):
                chi_gmean_test_c = chi.chi_quad(test_d_c[:, j])
                SSE_c += (chi_gmean_test_c - test_label_gmean_c[j]) ** 2
            SSEs_c[i, 3] = SSE_c / np.size(test_d_c)
#             print('\nUnseen data SSE', SSE_c)


#         print('\n\n\n')
        
        SSEs_all += SSEs
        SSEs_c_all += SSEs_c
        
        
SSEs_avg = SSEs_all / num_epoch
SSEs_c_avg = SSEs_c_all / num_epoch

  0%|          | 0/120 [00:00<?, ?it/s]

Train data ready
Train data superset size: (5, 6000)
Test data ready
Test data superset size: (5, 6000)
Epoch 0


 42%|████▏     | 50/120 [01:41<02:48,  2.41s/it]

In [10]:
fig, ax = plt.subplots()
x = (np.asarray(list(range(1, len(all_perms)+1)))) / len(all_perms)
print(x.shape, SSEs_avg.shape)
print(x)
print(SSEs_avg)
plt.plot(x, SSEs_avg)
ax.set_title('SSE (Data with same pattern)')
ax.legend(['Min', 'Max', 'Mean', 'Geometric Mean'])
ax.set_xlabel('Percentage of Seen Data')
ax.set_ylabel('SSEs avg')
ax.xaxis.set_major_formatter(FuncFormatter('{0:.0%}'.format))

plt.show()



fig, ax = plt.subplots()
x = (np.asarray(list(range(1, len(all_perms))))) / len(all_perms)
print(x.shape, SSEs_c_avg.shape)
print(x)
print(SSEs_c_avg)
plt.plot(x, SSEs_c_avg)
ax.set_title('SSE (Data with unseen pattern)')
ax.legend(['Min', 'Max', 'Mean', 'Geometric Mean'])
ax.set_xlabel('Percentage of Seen Data')
ax.set_ylabel('SSEs avg')
ax.xaxis.set_major_formatter(FuncFormatter('{0:.0%}'.format))

plt.show()

(24,) (24, 4)
[0.04166667 0.08333333 0.125      0.16666667 0.20833333 0.25
 0.29166667 0.33333333 0.375      0.41666667 0.45833333 0.5
 0.54166667 0.58333333 0.625      0.66666667 0.70833333 0.75
 0.79166667 0.83333333 0.875      0.91666667 0.95833333 1.        ]
[[1.72256182e-07 2.52120414e-07 1.75379035e-13 8.13767658e-03]
 [1.61810165e-07 3.35168000e-07 1.55012595e-10 7.58326466e-03]
 [1.07228199e-07 3.99371183e-07 1.30722644e-10 1.08291327e-02]
 [9.17165710e-08 4.59542377e-07 7.19617171e-10 9.41829009e-03]
 [7.95029652e-08 1.02255065e-06 1.54610808e-12 8.25478317e-03]
 [7.04562840e-08 1.00003912e-06 3.57301794e-12 8.36678800e-03]
 [5.67735073e-08 8.29527859e-07 5.85720131e-12 7.23061358e-03]
 [9.08447339e-08 7.38918724e-07 7.69687490e-12 7.15036539e-03]
 [1.30423108e-07 6.37696225e-07 1.70751582e-11 6.28244065e-03]
 [1.06124844e-07 4.93847514e-07 3.08682102e-12 5.99985349e-03]
 [8.66470602e-08 4.15525607e-07 2.26244674e-11 5.33347284e-03]
 [7.12319789e-08 3.65991452e-07 2.87756947e